#!/bin/sh -e
# prerm script for dima
#
# see: dh_installdeb(1)

case "$1" in
    purge|remove|abort-install|disappear)
        systemctl is-active --quiet nginx && systemctl stop nginx &>/dev/null || :
    ;;

    upgrade|failed-upgrade|abort-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
