name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build package
      run: |
        ls -la
        cd DEB-package
        ls -la
        docker build -t test:v1 .
        docker run -it --name test test:v1
